name: metapix
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.0=py36_0
  - astor=0.7.1=py_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_1
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.14.12=h80bd089_1005
  - certifi=2019.9.11=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - cloudpickle=1.2.2=py_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py_1
  - cytoolz=0.10.0=py36h516909a_0
  - dask-core=2.5.2=py_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.4.0=py_0
  - dominate=2.4.0=py_0
  - expat=2.2.5=he1b5a44_1003
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.2=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=hf484d3e_1000
  - grpcio=1.23.0=py36he9ae1f9_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.8.0=py36h3010b51_1003
  - harfbuzz=1.9.0=he243708_1001
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=hf484d3e_1000
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=habf39ab_1
  - keras=2.3.0=py36_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.65.3=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1000
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=h8b12597_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - mako=1.1.0=py_0
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=2.2.2=py36hb69df0a_2
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - mock=3.0.5=py36_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.3=0
  - networkx=2.3=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.2=py36haad9e8e_0
  - numpy-base=1.17.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1c=h516909a_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.2.3=py36_0
  - pixman=0.34.0=h14c3975_1003
  - protobuf=3.9.2=py36he1b5a44_1
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.19=py36_0
  - pygpu=0.7.6=py36h3010b51_1000
  - pyparsing=2.4.2=py_0
  - pyqt=5.6.0=py36h13b7fb3_1008
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py_0
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py36hd352d35_1
  - pyyaml=5.1.2=py36h516909a_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.2=py36hf484d3e_0
  - scipy=1.3.1=py36h7c811a0_0
  - setuptools=41.2.0=py36_0
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.12.0=py36_0
  - sqlite=3.30.0=h7b6447c_0
  - tensorboard=1.13.1=py36_0
  - tensorflow=1.13.1=h76b4ce7_7
  - tensorflow-base=1.13.1=py36h76b4ce7_7
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py_2
  - theano=1.0.4=py36hf484d3e_1000
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.2.1=py36_1000
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.36.1=py_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - click==7.0
    - flask==1.1.1
    - html4vision==0.3.0
    - itsdangerous==1.1.0
    - jinja2==2.10.3
prefix: /home/jl5/anaconda3/envs/metapix

